data_source dbsource:
     type: snowflake
     username: josraj
     password: Login2SF!
     account: kd30072.central-india.azure
     database: DBT_DB
     warehouse: compute_wh
     role: 
     session_parameters:
       QUERY_TAG: soda-queries
       QUOTED_IDENTIFIERS_IGNORE_CASE: false
     schema: DBT_SCHEMA
      
soda_cloud:
     host: cloud.soda.io
     api_key_id: b9caaff5-90fa-433e-bf72-c6cc2f8c07a2
     api_key_secret: kaD5CD3c65tLlEl5j38K4-I324XliCjF80obJ0gocWdrlSOgI9kvtA
